int16 CONNECTING = 0
int16 OK = 1
int16 WAITING_FOR_REBOOT = 2
int16 UPLOADING_FIRMWARE = 3
int16 UPLOADING_BATTERY_FIRMWARE = 4
int16 NO_TEENSIES = -100
int16 UNABLE_TO_GET_VERSION = -101
int16 NO_FIRMWARE_AVAILABLE = -102
int16 NO_FIRMWARE_FOR_THIS_TEENSY = -103
int16 UPGRADE_FAILED = -104
int16 CONNECTION_FAILED = -105
int16 MULTIPLE_TEENSIES = -106
int16 DISCONNECTED = -200

int16 state
---
bool success
